import Head from 'next/head'
import Header from '@/component/Header';
import Footer from '@/component/Footer';
import Product from '@/component/Product';
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Product/>

      <Footer />
    </>
  )
}
